### ISSUE TITLE
Bug with string interpolation and pipe syntax.

### ISSUE THREAD

**Issue by jaymanmdev** [dibsonthis/sprig#1]
Hi there, first of all - this is a really cool idea! And a great start! I'll be playing around with it and probably building some stuff in Node with it.

First of all, I realised that you say that this language is dynamic for now, does that mean that static typing might be coming in the future? :o That would be great! One of the reasons I am not a huge fan of Javascript is because of its loosy goosiness, and imo Typescript just isn't a good linter on top of Javascript.

And secondly, I have quickly come across a bug with using string interpolation with a string piped into a function like so:
![image](https://github.com/user-attachments/assets/c4a0115b-ac3a-4bb8-90a1-a5b76c658bca)
The output to this is:
![image](https://github.com/user-attachments/assets/d253b278-8106-4b40-ab80-03289e341094)

Whereas with:
![image](https://github.com/user-attachments/assets/30031594-a969-4012-ad4e-be9bdf79d833)
The output is as expected:
![image](https://github.com/user-attachments/assets/a0922e8f-2fc1-4823-a22b-4036dc953581)

Thanks!

**Comment by dibsonthis** [comment]
Thanks for checking out Sprig! Looking forward to seeing what you come up with 😃

Yep, hoping to work on a static analysis compilation phase soon. So hopefully I can introduce some cool type safety features in the near future!

Thanks for raising that issue - I know why that's happening. String interpolation is really just syntactic sugar for eval(statement) + "..." + eval(statement) and thus it's only piping the last piece of that which is the dot.

If you wrap the string in parentheses that should fix the issue. But I'll work on a fix for this so you won't have to do that in the future 🙂

**Comment by dibsonthis** [comment]
Alright, fix is in: https://github.com/dibsonthis/sprig/commit/09b15d834df7f0b0742dc440c8de4723b423ebaa

```
const greet = (start, name) => `{{start}} {{name}}.`->print
"Hello"->greet("Anthony") // Hello Anthony.
```

Please let me know if that's working so we can close the issue 😃
